package:
  name: spyking-circus
  version: "0.5"

requirements:
  build:
    - python
    - progressbar2
    - mpi4py
    - numpy
    - cython
    - scipy
    - matplotlib
    - h5py
    - setuptools
    - colorama
    - psutil
    - scikit-learn
  run:
    - python
    - progressbar2
    - mpi4py
    - numpy
    - cython
    - scipy
    - matplotlib
    - h5py
    - setuptools
    - colorama
    - qt
    - pyqt >=4,<=5
    - scikit-learn
source:
  path: ..

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt

test:
  # Python imports
  imports:
    - circus
    - circus.shared
    - circus.scripts
  commands:
    - spyking-circus -h

about:
  home: http://spyking-circus.rtfd.org
  license: CEA CNRS Inria Logiciel Libre License, version 2.1 (CeCILL-2.1)
  summary: 'Fast spike sorting by template matching'
